### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by whu-lee** [ajhamdi/MVTN#3]
Thank you very much for your reply. Sorry I have encountered another problem.
What is the use of the weights under results/checkpoints/modelnet/?
Could you provide the model weights for the best results?

**Comment by ajhamdi** [comment]
These are the weights of a ResNet18 pretrained on ModelNet40. This is required in the ViewGCN paper in order to do two-stage training where the first is single-view and the second is multi-view. The weights are provided to avoid doing the first stage, and they will be ignored if you end up doing the two stages by passing the flag `--viewgcn_phase all`
